services:


  postgres:
    container_name: postgres
    image: postgres:17.4
    restart: always
    networks:
      - carpooling-network
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - carpooling-network
    ports:
      - "8082:8080"

  redis:
    container_name: redis
    image: redis:8.0-rc1
    restart: always
    networks:
      - carpooling-network
    env_file:
      - .env
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  carpooling-app:
    build: .
    depends_on:
      - postgres
      - redis
    networks:
      - carpooling-network
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}?currentSchema=public
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "8080:8080"

networks:
  carpooling-network:
    driver: bridge

volumes:
  pg_data:
  redis_data: