version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.24

      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
            - gradle-cache-

      - run:
          name: Setup Gradle wrapper
          command: ./gradlew wrapper

      - run:
          name: Build & run tests
          command: ./gradlew clean test jacocoTestReport --no-daemon

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "build.gradle" }}

      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

      - run:
          name: Run SonarCloud analysis with Gradle
          command: ./gradlew sonar --no-daemon